### PR TITLE
support redis config as list

### PR DESCRIPTION
**Pull request by erikosmond**
Greetings, I have a config provider (aws_ssm_provider) that merges each value one at a time, but into a list. This change would allow me to continue using my config provider and start using exq-scheduler. Please let me know if you'd like any modifications.

### CODE REVIEW

**Comment by ananthakumaran** [comment]
Sorry, I missed this issue earlier. I don't understand why the config can't be formatted. You could probably point me to some documentation or other libraries which support this kind of format.

**Comment by erikosmond** [comment]
@ananthakumaran Thank you for the reply. My config provider builds configs as keyword lists, as described here: https://hexdocs.pm/elixir/master/Config.html#config/2. This is the only library where the config provider has not worked seamlessly, including redix, ecto, exq, etc.

**Comment by erikosmond** [comment]
@ananthakumaran I understand your point "why can't the config be specified as the expected format". It's a fair point. In our case, however, we store our configs in AWS SSM with one record per value. For example, we use

/staging/scheduling/exq_scheduler/redis/child_spec/Elixir.Redix/host -> "clusterHost"
/staging/scheduling/exq_scheduler/redis/child_spec/Elixir.Redix/name -> "clusterName"

as opposed to what I believe your library expects:
/staging/scheduling/exq_scheduler/redis/child_spec/Elixir.Redix -> %{host: "clusterHost", name: "clusterName"}

The config provider we use converts the multiple records in SSM into a keyword list as opposed to a map. Is there a problem with my implementation to patch exq_scheduler to support Keyword lists, which are very common config types in mix projects?

Thanks for your consideration!

**Comment by ananthakumaran** [comment]
The spec of the config is the same as the elixir [`child_spec`](https://hexdocs.pm/elixir/1.12/Supervisor.html#module-child-specification). The value is passed straight down to the supervisor.

I am assuming your library can't generate a tuple or map? I don't see how the patch would fix the issue though. You would still need to generate `[{Redix, ["redis://localhost:6379", [name: ExqScheduler.Redis.Client]]}]` which requires tuple.

You could use a custom module as a workaround.

```elixir
config :exq_scheduler, :redis,
  name: ExqScheduler.Redis.Client,
  child_spec: RedixConfig

defmodule RedixConfig do
  def child_spec([])
    Redix.child_spec(["redis://localhost:6379", [name: ExqScheduler.Redis.Client]])
  end
end
```

The reason I just stick to child_spec is, it's elixir standard and the user is allowed to tweak the config as necessary. Specially, if Redix library changed the config format, they don't have to wait for exq_scheduler to support the new format. It also allowed using RedixSentinel library in the past.

**Pull request closed without merging**
